version: "3"
services:
  go:
    environment:
      - MONGO_DB=recipes
      - MONGO_URI=mongodb://db:27017/recipes
    restart: always
    build: .
    ports:
      - 3000:3000
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
