# Use postgres/example user/password credentials
version: "3.7"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:3001
    depends_on:
      - db
    links:
      - "db:db"

volumes:
  data:
