# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test_backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn test

  test_frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn test:unit
